// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ConsoleApp1.Contexts;
using ConsoleApp1.DbFirsrtModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace ConsoleApp1.Contexts.Configurations
{
    public partial class RefObjCharConfiguration : IEntityTypeConfiguration<RefObjChar>
    {
        public void Configure(EntityTypeBuilder<RefObjChar> entity)
        {
            entity
                .HasNoKey()
                .ToTable("_RefObjChar");

            entity.Property(e => e.Br).HasColumnName("BR");
            entity.Property(e => e.CanStoreTid1).HasColumnName("CanStore_TID1");
            entity.Property(e => e.CanStoreTid2).HasColumnName("CanStore_TID2");
            entity.Property(e => e.CanStoreTid3).HasColumnName("CanStore_TID3");
            entity.Property(e => e.CanStoreTid4).HasColumnName("CanStore_TID4");
            entity.Property(e => e.Chr).HasColumnName("CHR");
            entity.Property(e => e.DefaultSkill1).HasColumnName("DefaultSkill_1");
            entity.Property(e => e.DefaultSkill10).HasColumnName("DefaultSkill_10");
            entity.Property(e => e.DefaultSkill2).HasColumnName("DefaultSkill_2");
            entity.Property(e => e.DefaultSkill3).HasColumnName("DefaultSkill_3");
            entity.Property(e => e.DefaultSkill4).HasColumnName("DefaultSkill_4");
            entity.Property(e => e.DefaultSkill5).HasColumnName("DefaultSkill_5");
            entity.Property(e => e.DefaultSkill6).HasColumnName("DefaultSkill_6");
            entity.Property(e => e.DefaultSkill7).HasColumnName("DefaultSkill_7");
            entity.Property(e => e.DefaultSkill8).HasColumnName("DefaultSkill_8");
            entity.Property(e => e.DefaultSkill9).HasColumnName("DefaultSkill_9");
            entity.Property(e => e.Er).HasColumnName("ER");
            entity.Property(e => e.Except1).HasColumnName("Except_1");
            entity.Property(e => e.Except10).HasColumnName("Except_10");
            entity.Property(e => e.Except2).HasColumnName("Except_2");
            entity.Property(e => e.Except3).HasColumnName("Except_3");
            entity.Property(e => e.Except4).HasColumnName("Except_4");
            entity.Property(e => e.Except5).HasColumnName("Except_5");
            entity.Property(e => e.Except6).HasColumnName("Except_6");
            entity.Property(e => e.Except7).HasColumnName("Except_7");
            entity.Property(e => e.Except8).HasColumnName("Except_8");
            entity.Property(e => e.Except9).HasColumnName("Except_9");
            entity.Property(e => e.Hr).HasColumnName("HR");
            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("ID");
            entity.Property(e => e.KoRecoverTime).HasColumnName("KO_RecoverTime");
            entity.Property(e => e.Mar).HasColumnName("MAR");
            entity.Property(e => e.MaxHp).HasColumnName("MaxHP");
            entity.Property(e => e.MaxMp).HasColumnName("MaxMP");
            entity.Property(e => e.Md).HasColumnName("MD");
            entity.Property(e => e.Par).HasColumnName("PAR");
            entity.Property(e => e.Pd).HasColumnName("PD");
            entity.Property(e => e.ResistCseHp).HasColumnName("ResistCseHP");
            entity.Property(e => e.ResistCseInt).HasColumnName("ResistCseINT");
            entity.Property(e => e.ResistCseMd).HasColumnName("ResistCseMD");
            entity.Property(e => e.ResistCseMp).HasColumnName("ResistCseMP");
            entity.Property(e => e.ResistCsePd).HasColumnName("ResistCsePD");
            entity.Property(e => e.ResistCseStr).HasColumnName("ResistCseSTR");
            entity.Property(e => e.ResistEshock).HasColumnName("ResistEShock");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RefObjChar> entity);
    }
}
