// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ConsoleApp1.Contexts;
using ConsoleApp1.DbFirsrtModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace ConsoleApp1.Contexts.Configurations
{
    public partial class RefObjItemConfiguration : IEntityTypeConfiguration<RefObjItem>
    {
        public void Configure(EntityTypeBuilder<RefObjItem> entity)
        {
            entity
                .HasNoKey()
                .ToTable("_RefObjItem");

            entity.Property(e => e.Ammo1Tid4).HasColumnName("Ammo1_TID4");
            entity.Property(e => e.Ammo2Tid4).HasColumnName("Ammo2_TID4");
            entity.Property(e => e.Ammo3Tid4).HasColumnName("Ammo3_TID4");
            entity.Property(e => e.Ammo4Tid4).HasColumnName("Ammo4_TID4");
            entity.Property(e => e.Ammo5Tid4).HasColumnName("Ammo5_TID4");
            entity.Property(e => e.BrL).HasColumnName("BR_L");
            entity.Property(e => e.BrU).HasColumnName("BR_U");
            entity.Property(e => e.ChrL).HasColumnName("CHR_L");
            entity.Property(e => e.ChrU).HasColumnName("CHR_U");
            entity.Property(e => e.Desc10128)
                .HasMaxLength(129)
                .IsUnicode(false)
                .HasColumnName("Desc10_128");
            entity.Property(e => e.Desc11128)
                .HasMaxLength(129)
                .IsUnicode(false)
                .HasColumnName("Desc11_128");
            entity.Property(e => e.Desc1128)
                .HasMaxLength(129)
                .IsUnicode(false)
                .HasColumnName("Desc1_128");
            entity.Property(e => e.Desc12128)
                .HasMaxLength(129)
                .IsUnicode(false)
                .HasColumnName("Desc12_128");
            entity.Property(e => e.Desc13128)
                .HasMaxLength(129)
                .IsUnicode(false)
                .HasColumnName("Desc13_128");
            entity.Property(e => e.Desc14128)
                .HasMaxLength(129)
                .IsUnicode(false)
                .HasColumnName("Desc14_128");
            entity.Property(e => e.Desc15128)
                .HasMaxLength(129)
                .IsUnicode(false)
                .HasColumnName("Desc15_128");
            entity.Property(e => e.Desc16128)
                .HasMaxLength(129)
                .IsUnicode(false)
                .HasColumnName("Desc16_128");
            entity.Property(e => e.Desc17128)
                .HasMaxLength(129)
                .IsUnicode(false)
                .HasColumnName("Desc17_128");
            entity.Property(e => e.Desc18128)
                .HasMaxLength(129)
                .IsUnicode(false)
                .HasColumnName("Desc18_128");
            entity.Property(e => e.Desc19128)
                .HasMaxLength(129)
                .IsUnicode(false)
                .HasColumnName("Desc19_128");
            entity.Property(e => e.Desc20128)
                .HasMaxLength(129)
                .IsUnicode(false)
                .HasColumnName("Desc20_128");
            entity.Property(e => e.Desc2128)
                .HasMaxLength(129)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("Desc2_128");
            entity.Property(e => e.Desc3128)
                .HasMaxLength(129)
                .IsUnicode(false)
                .HasColumnName("Desc3_128");
            entity.Property(e => e.Desc4128)
                .HasMaxLength(129)
                .IsUnicode(false)
                .HasColumnName("Desc4_128");
            entity.Property(e => e.Desc5128)
                .HasMaxLength(129)
                .IsUnicode(false)
                .HasColumnName("Desc5_128");
            entity.Property(e => e.Desc6128)
                .HasMaxLength(129)
                .IsUnicode(false)
                .HasColumnName("Desc6_128");
            entity.Property(e => e.Desc7128)
                .HasMaxLength(129)
                .IsUnicode(false)
                .HasColumnName("Desc7_128");
            entity.Property(e => e.Desc8128)
                .HasMaxLength(129)
                .IsUnicode(false)
                .HasColumnName("Desc8_128");
            entity.Property(e => e.Desc9128)
                .HasMaxLength(129)
                .IsUnicode(false)
                .HasColumnName("Desc9_128");
            entity.Property(e => e.DurL).HasColumnName("Dur_L");
            entity.Property(e => e.DurU).HasColumnName("Dur_U");
            entity.Property(e => e.ErL).HasColumnName("ER_L");
            entity.Property(e => e.ErU).HasColumnName("ER_U");
            entity.Property(e => e.Erinc).HasColumnName("ERInc");
            entity.Property(e => e.HrL).HasColumnName("HR_L");
            entity.Property(e => e.HrU).HasColumnName("HR_U");
            entity.Property(e => e.Hrinc).HasColumnName("HRInc");
            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("ID");
            entity.Property(e => e.MaintMaxL).HasColumnName("MAInt_Max_L");
            entity.Property(e => e.MaintMaxU).HasColumnName("MAInt_Max_U");
            entity.Property(e => e.MaintMinL).HasColumnName("MAInt_Min_L");
            entity.Property(e => e.MaintMinU).HasColumnName("MAInt_Min_U");
            entity.Property(e => e.MarL).HasColumnName("MAR_L");
            entity.Property(e => e.MarU).HasColumnName("MAR_U");
            entity.Property(e => e.Marinc).HasColumnName("MARInc");
            entity.Property(e => e.MattackInc).HasColumnName("MAttackInc");
            entity.Property(e => e.MattackMaxL).HasColumnName("MAttackMax_L");
            entity.Property(e => e.MattackMaxU).HasColumnName("MAttackMax_U");
            entity.Property(e => e.MattackMinL).HasColumnName("MAttackMin_L");
            entity.Property(e => e.MattackMinU).HasColumnName("MAttackMin_U");
            entity.Property(e => e.MdL).HasColumnName("MD_L");
            entity.Property(e => e.MdU).HasColumnName("MD_U");
            entity.Property(e => e.Mdinc).HasColumnName("MDInc");
            entity.Property(e => e.MdintL).HasColumnName("MDInt_L");
            entity.Property(e => e.MdintU).HasColumnName("MDInt_U");
            entity.Property(e => e.ParL).HasColumnName("PAR_L");
            entity.Property(e => e.ParU).HasColumnName("PAR_U");
            entity.Property(e => e.Parinc).HasColumnName("PARInc");
            entity.Property(e => e.PastrMaxL).HasColumnName("PAStrMax_L");
            entity.Property(e => e.PastrMaxU).HasColumnName("PAStrMax_U");
            entity.Property(e => e.PastrMinL).HasColumnName("PAStrMin_L");
            entity.Property(e => e.PastrMinU).HasColumnName("PAStrMin_U");
            entity.Property(e => e.PattackInc).HasColumnName("PAttackInc");
            entity.Property(e => e.PattackMaxL).HasColumnName("PAttackMax_L");
            entity.Property(e => e.PattackMaxU).HasColumnName("PAttackMax_U");
            entity.Property(e => e.PattackMinL).HasColumnName("PAttackMin_L");
            entity.Property(e => e.PattackMinU).HasColumnName("PAttackMin_U");
            entity.Property(e => e.PdL).HasColumnName("PD_L");
            entity.Property(e => e.PdU).HasColumnName("PD_U");
            entity.Property(e => e.Pdinc).HasColumnName("PDInc");
            entity.Property(e => e.PdstrL).HasColumnName("PDStr_L");
            entity.Property(e => e.PdstrU).HasColumnName("PDStr_U");
            entity.Property(e => e.SetId).HasColumnName("SetID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RefObjItem> entity);
    }
}
