// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ConsoleApp1.Contexts;
using ConsoleApp1.DbFirsrtModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace ConsoleApp1.Contexts.Configurations
{
    public partial class RefObjStructConfiguration : IEntityTypeConfiguration<RefObjStruct>
    {
        public void Configure(EntityTypeBuilder<RefObjStruct> entity)
        {
            entity
                .HasNoKey()
                .ToTable("_RefObjStruct");

            entity.Property(e => e.DummyData).HasColumnName("Dummy_Data");
            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("ID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RefObjStruct> entity);
    }
}
