// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ConsoleApp1.Contexts;
using ConsoleApp1.DbFirsrtModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace ConsoleApp1.Contexts.Configurations
{
    public partial class RefObjCommonConfiguration : IEntityTypeConfiguration<RefObjCommon>
    {
        public void Configure(EntityTypeBuilder<RefObjCommon> entity)
        {
            entity.HasKey(e => e.Id).HasFillFactor(90);

            entity.ToTable("_RefObjCommon");

            entity.HasIndex(e => e.CodeName128, "IX_RefObjCommon_CodeName").HasFillFactor(90);

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AssocFile1128)
                .HasMaxLength(129)
                .IsUnicode(false)
                .HasColumnName("AssocFile1_128");
            entity.Property(e => e.AssocFile2128)
                .HasMaxLength(129)
                .IsUnicode(false)
                .HasColumnName("AssocFile2_128");
            entity.Property(e => e.AssocFileDrop128)
                .HasMaxLength(129)
                .IsUnicode(false);
            entity.Property(e => e.AssocFileIcon128)
                .HasMaxLength(129)
                .IsUnicode(false);
            entity.Property(e => e.AssocFileObj128)
                .HasMaxLength(129)
                .IsUnicode(false);
            entity.Property(e => e.Bcheight).HasColumnName("BCHeight");
            entity.Property(e => e.Bcradius).HasColumnName("BCRadius");
            entity.Property(e => e.CodeName128)
                .HasMaxLength(129)
                .IsUnicode(false);
            entity.Property(e => e.DescStrId128)
                .HasMaxLength(129)
                .IsUnicode(false)
                .HasColumnName("DescStrID128");
            entity.Property(e => e.EventId).HasColumnName("EventID");
            entity.Property(e => e.NameStrId128)
                .HasMaxLength(129)
                .IsUnicode(false)
                .HasColumnName("NameStrID128");
            entity.Property(e => e.ObjName128)
                .HasMaxLength(129)
                .IsUnicode(false);
            entity.Property(e => e.OrgObjCodeName128)
                .HasMaxLength(129)
                .IsUnicode(false);
            entity.Property(e => e.RegionId).HasColumnName("RegionID");
            entity.Property(e => e.TypeId1).HasColumnName("TypeID1");
            entity.Property(e => e.TypeId2).HasColumnName("TypeID2");
            entity.Property(e => e.TypeId3).HasColumnName("TypeID3");
            entity.Property(e => e.TypeId4).HasColumnName("TypeID4");
            entity.Property(e => e.WebName)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasDefaultValue("ItemName")
                .HasColumnName("webName");
            entity.Property(e => e.WebNumber).HasColumnName("webNumber");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RefObjCommon> entity);
    }
}
