// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ConsoleApp1.Contexts;
using ConsoleApp1.DbFirsrtModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace ConsoleApp1.Contexts.Configurations
{
    public partial class TimItemOnCharConfiguration : IEntityTypeConfiguration<TimItemOnChar>
    {
        public void Configure(EntityTypeBuilder<TimItemOnChar> entity)
        {
            entity
                .HasNoKey()
                .ToView("TimItemOnChar");

            entity.Property(e => e.CharId).HasColumnName("CharID");
            entity.Property(e => e.CharName16)
                .HasMaxLength(64)
                .IsUnicode(false)
                .UseCollation("Latin1_General_CI_AS");
            entity.Property(e => e.CreaterName)
                .HasMaxLength(64)
                .IsUnicode(false)
                .UseCollation("Latin1_General_CI_AS");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TimItemOnChar> entity);
    }
}
