// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ConsoleApp1.DbFirsrtModels;

public partial class RefObjItem
{
    public int Id { get; set; }

    public int MaxStack { get; set; }

    public byte ReqGender { get; set; }

    public int ReqStr { get; set; }

    public int ReqInt { get; set; }

    public byte ItemClass { get; set; }

    public int SetId { get; set; }

    public float DurL { get; set; }

    public float DurU { get; set; }

    public float PdL { get; set; }

    public float PdU { get; set; }

    public float Pdinc { get; set; }

    public float ErL { get; set; }

    public float ErU { get; set; }

    public float Erinc { get; set; }

    public float ParL { get; set; }

    public float ParU { get; set; }

    public float Parinc { get; set; }

    public float BrL { get; set; }

    public float BrU { get; set; }

    public float MdL { get; set; }

    public float MdU { get; set; }

    public float Mdinc { get; set; }

    public float MarL { get; set; }

    public float MarU { get; set; }

    public float Marinc { get; set; }

    public float PdstrL { get; set; }

    public float PdstrU { get; set; }

    public float MdintL { get; set; }

    public float MdintU { get; set; }

    public byte Quivered { get; set; }

    public byte Ammo1Tid4 { get; set; }

    public byte Ammo2Tid4 { get; set; }

    public byte Ammo3Tid4 { get; set; }

    public byte Ammo4Tid4 { get; set; }

    public byte Ammo5Tid4 { get; set; }

    public byte SpeedClass { get; set; }

    public byte TwoHanded { get; set; }

    public short Range { get; set; }

    public float PattackMinL { get; set; }

    public float PattackMinU { get; set; }

    public float PattackMaxL { get; set; }

    public float PattackMaxU { get; set; }

    public float PattackInc { get; set; }

    public float MattackMinL { get; set; }

    public float MattackMinU { get; set; }

    public float MattackMaxL { get; set; }

    public float MattackMaxU { get; set; }

    public float MattackInc { get; set; }

    public float PastrMinL { get; set; }

    public float PastrMinU { get; set; }

    public float PastrMaxL { get; set; }

    public float PastrMaxU { get; set; }

    public float MaintMinL { get; set; }

    public float MaintMinU { get; set; }

    public float MaintMaxL { get; set; }

    public float MaintMaxU { get; set; }

    public float HrL { get; set; }

    public float HrU { get; set; }

    public float Hrinc { get; set; }

    public float ChrL { get; set; }

    public float ChrU { get; set; }

    public int Param1 { get; set; }

    public string Desc1128 { get; set; } = null!;

    public int Param2 { get; set; }

    public string Desc2128 { get; set; } = null!;

    public int Param3 { get; set; }

    public string Desc3128 { get; set; } = null!;

    public int Param4 { get; set; }

    public string Desc4128 { get; set; } = null!;

    public int Param5 { get; set; }

    public string Desc5128 { get; set; } = null!;

    public int Param6 { get; set; }

    public string Desc6128 { get; set; } = null!;

    public int Param7 { get; set; }

    public string Desc7128 { get; set; } = null!;

    public int Param8 { get; set; }

    public string Desc8128 { get; set; } = null!;

    public int Param9 { get; set; }

    public string Desc9128 { get; set; } = null!;

    public int Param10 { get; set; }

    public string Desc10128 { get; set; } = null!;

    public int Param11 { get; set; }

    public string Desc11128 { get; set; } = null!;

    public int Param12 { get; set; }

    public string Desc12128 { get; set; } = null!;

    public int Param13 { get; set; }

    public string Desc13128 { get; set; } = null!;

    public int Param14 { get; set; }

    public string Desc14128 { get; set; } = null!;

    public int Param15 { get; set; }

    public string Desc15128 { get; set; } = null!;

    public int Param16 { get; set; }

    public string Desc16128 { get; set; } = null!;

    public int Param17 { get; set; }

    public string Desc17128 { get; set; } = null!;

    public int Param18 { get; set; }

    public string Desc18128 { get; set; } = null!;

    public int Param19 { get; set; }

    public string Desc19128 { get; set; } = null!;

    public int Param20 { get; set; }

    public string Desc20128 { get; set; } = null!;

    public byte MaxMagicOptCount { get; set; }

    public byte ChildItemCount { get; set; }

    public int Link { get; set; }
}