// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ConsoleApp1.DbFirsrtModels;

public partial class RefObjStruct
{
    public int Id { get; set; }

    public int DummyData { get; set; }
}