// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ConsoleApp1.DbFirsrtModels;

public partial class TimItemOnChar
{
    public int CharId { get; set; }

    public string CharName16 { get; set; } = null!;

    public byte? OptLevel { get; set; }

    public long? Variance { get; set; }

    public int Data { get; set; }

    public byte MagParamNum { get; set; }

    public string? CreaterName { get; set; }

    public long? MagParam1 { get; set; }

    public long? MagParam2 { get; set; }

    public long? MagParam3 { get; set; }

    public long? MagParam4 { get; set; }

    public long? MagParam5 { get; set; }

    public long? MagParam6 { get; set; }

    public long? MagParam7 { get; set; }

    public long? MagParam8 { get; set; }

    public long? MagParam9 { get; set; }

    public long? MagParam10 { get; set; }

    public long? MagParam11 { get; set; }

    public long? MagParam12 { get; set; }

    public long Serial64 { get; set; }
}